version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/code
    depends_on:
      - db
  
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'agenda'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db: