# Generated by Django 4.1.4 on 2022-12-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compromisso', models.CharField(max_length=255)),
                ('data_hora', models.DateTimeField()),
                ('cliente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'agenda',
            },
        ),
    ]
