# Generated by Django 4.1.4 on 2022-12-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_app', '0002_agenda_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='celular',
            field=models.CharField(max_length=11),
        ),
    ]
